#!/bin/bash
#=================================================================================
# Copyright (C) Andrzej Adamczyk (at https://blackdev.org/). All rights reserved.
#=================================================================================

clear

# default CPUs amount: 2
SMP="${1}"
if [ -z "${SMP}" ]; then SMP="2"; fi

# default Memory size: 64 MiB
MEM="${2}"
if [ -z "${MEM}" ]; then MEM="64"; fi

qemu-system-x86_64				\
	--enable-kvm				\
	-cpu max				\
	-smp ${SMP}				\
	-m ${MEM}				\
	-cdrom build/cyjon.iso			\
	-rtc base=localtime			\
	-audio driver=alsa,model=sb16,id=7	\
	-serial stdio				\
#	-usb -device usb-mouse,id=mouse		\
#	-usb -device usb-kbd,id=keyboard	\
